export const books = [
  {
    id: 1,
    category: "Fiction",
    title: "To Kill a Mockingbird",
    coverImage: "https://covers.openlibrary.org/b/id/8384476-L.jpg",
    description:
      "A novel about racial injustice and moral growth in the American South.",
    authorName: "Harper Lee",
    dateOfPublication: "1960-07-11",
    numberOfPages: 281,
    rating: 4.27,
  },
  {
    id: 2,
    category: "Fiction",
    title: "1984",
    coverImage: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
    description: "A dystopian novel about totalitarianism and surveillance.",
    authorName: "George Orwell",
    dateOfPublication: "1949-06-08",
    numberOfPages: 328,
    rating: 4.19,
  },
  {
    id: 3,
    category: "Non-Fiction",
    title: "Sapiens: A Brief History of Humankind",
    coverImage: "https://covers.openlibrary.org/b/id/8576056-L.jpg",
    description:
      "Explores the history of Homo sapiens from evolution to modern society.",
    authorName: "Yuval Noah Harari",
    dateOfPublication: "2011-02-10",
    numberOfPages: 443,
    rating: 4.37,
  },
  {
    id: 4,
    category: "Science",
    title: "A Brief History of Time",
    coverImage: "https://covers.openlibrary.org/b/id/8437632-L.jpg",
    description:
      "Stephen Hawking's exploration of cosmology for general readers.",
    authorName: "Stephen Hawking",
    dateOfPublication: "1988-01-01",
    numberOfPages: 212,
    rating: 4.18,
  },
  {
    id: 5,
    category: "Biography",
    title: "The Diary of a Young Girl",
    coverImage: "https://covers.openlibrary.org/b/id/8396675-L.jpg",
    description: "Anne Frank's diary during WWII hiding in Amsterdam.",
    authorName: "Anne Frank",
    dateOfPublication: "1947-06-25",
    numberOfPages: 283,
    rating: 4.16,
  },
  {
    id: 6,
    category: "Fiction",
    title: "The Great Gatsby",
    coverImage: "https://covers.openlibrary.org/b/id/8396676-L.jpg",
    description:
      "A story of wealth, love, and the American Dream in the 1920s.",
    authorName: "F. Scott Fitzgerald",
    dateOfPublication: "1925-04-10",
    numberOfPages: 180,
    rating: 3.93,
  },
  {
    id: 7,
    category: "Non-Fiction",
    title: "Atomic Habits",
    coverImage: "https://covers.openlibrary.org/b/id/10309848-L.jpg",
    description: "A guide to building good habits and breaking bad ones.",
    authorName: "James Clear",
    dateOfPublication: "2018-10-16",
    numberOfPages: 319,
    rating: 4.36,
  },
  {
    id: 8,
    category: "Science",
    title: "Cosmos",
    coverImage: "https://covers.openlibrary.org/b/id/8396677-L.jpg",
    description:
      "Carl Sagan's exploration of the universe and humanity's place in it.",
    authorName: "Carl Sagan",
    dateOfPublication: "1980-01-01",
    numberOfPages: 365,
    rating: 4.39,
  },
  {
    id: 9,
    category: "Biography",
    title: "Steve Jobs",
    coverImage: "https://covers.openlibrary.org/b/id/8396678-L.jpg",
    description: "Walter Isaacson's biography of Apple co-founder Steve Jobs.",
    authorName: "Walter Isaacson",
    dateOfPublication: "2011-10-24",
    numberOfPages: 630,
    rating: 4.15,
  },
  {
    id: 10,
    category: "Fiction",
    title: "Pride and Prejudice",
    coverImage: "https://covers.openlibrary.org/b/id/8396679-L.jpg",
    description:
      "A romantic novel about Elizabeth Bennet and Mr. Darcy in 19th-century England.",
    authorName: "Jane Austen",
    dateOfPublication: "1813-01-28",
    numberOfPages: 279,
    rating: 4.28,
  },
  {
    id: 11,
    category: "Non-Fiction",
    title: "The Subtle Art of Not Giving a F*ck",
    coverImage: "https://covers.openlibrary.org/b/id/8396680-L.jpg",
    description: "A counterintuitive approach to living a good life.",
    authorName: "Mark Manson",
    dateOfPublication: "2016-09-13",
    numberOfPages: 224,
    rating: 3.9,
  },
  {
    id: 12,
    category: "Science",
    title: "The Selfish Gene",
    coverImage: "https://covers.openlibrary.org/b/id/8396681-L.jpg",
    description:
      "Richard Dawkins explains evolution through gene-centered selection.",
    authorName: "Richard Dawkins",
    dateOfPublication: "1976-01-01",
    numberOfPages: 224,
    rating: 4.12,
  },
  {
    id: 13,
    category: "Biography",
    title: "Long Walk to Freedom",
    coverImage: "https://covers.openlibrary.org/b/id/8396682-L.jpg",
    description:
      "Nelson Mandela's autobiography about his fight against apartheid.",
    authorName: "Nelson Mandela",
    dateOfPublication: "1994-12-01",
    numberOfPages: 656,
    rating: 4.35,
  },
  {
    id: 14,
    category: "Fiction",
    title: "The Hobbit",
    coverImage: "https://covers.openlibrary.org/b/id/8396683-L.jpg",
    description:
      "A fantasy novel about Bilbo Baggins' adventure to reclaim treasure.",
    authorName: "J.R.R. Tolkien",
    dateOfPublication: "1937-09-21",
    numberOfPages: 310,
    rating: 4.28,
  },
  {
    id: 15,
    category: "Non-Fiction",
    title: "Thinking, Fast and Slow",
    coverImage: "https://covers.openlibrary.org/b/id/8396684-L.jpg",
    description: "Daniel Kahneman's exploration of human decision-making.",
    authorName: "Daniel Kahneman",
    dateOfPublication: "2011-10-25",
    numberOfPages: 499,
    rating: 4.18,
  },
  {
    id: 16,
    category: "Fiction",
    title: "Pride and Prejudice",
    coverImage: "https://covers.openlibrary.org/b/id/8396679-L.jpg",
    description:
      "A romantic novel about Elizabeth Bennet and Mr. Darcy in 19th-century England.",
    authorName: "Jane Austen",
    dateOfPublication: "1813-01-28",
    numberOfPages: 279,
    rating: 4.28,
  },
  {
    id: 17,
    category: "Non-Fiction",
    title: "The Subtle Art of Not Giving a F*ck",
    coverImage: "https://covers.openlibrary.org/b/id/8396680-L.jpg",
    description: "A counterintuitive approach to living a good life.",
    authorName: "Mark Manson",
    dateOfPublication: "2016-09-13",
    numberOfPages: 224,
    rating: 3.9,
  },
  {
    id: 18,
    category: "Science",
    title: "The Selfish Gene",
    coverImage: "https://covers.openlibrary.org/b/id/8396681-L.jpg",
    description:
      "Richard Dawkins explains evolution through gene-centered selection.",
    authorName: "Richard Dawkins",
    dateOfPublication: "1976-01-01",
    numberOfPages: 224,
    rating: 4.12,
  },
  {
    id: 19,
    category: "Biography",
    title: "Long Walk to Freedom",
    coverImage: "https://covers.openlibrary.org/b/id/8396682-L.jpg",
    description:
      "Nelson Mandela's autobiography about his fight against apartheid.",
    authorName: "Nelson Mandela",
    dateOfPublication: "1994-12-01",
    numberOfPages: 656,
    rating: 4.35,
  },

  {
    id: 20,
    category: "Biography",
    title: "Long Walk to Freedom",
    coverImage: "https://covers.openlibrary.org/b/id/8396682-L.jpg",
    description:
      "Nelson Mandela's autobiography about his fight against apartheid.",
    authorName: "Nelson Mandela",
    dateOfPublication: "1994-12-01",
    numberOfPages: 656,
    rating: 4.35,
  },
  {
    id: 21,
    category: "Science",
    title: "A Brief History of Time",
    coverImage: "https://covers.openlibrary.org/b/id/240726-L.jpg",
    description:
      "Stephen Hawking explores black holes and the origin of the universe.",
    authorName: "Stephen Hawking",
    dateOfPublication: "1988-03-01",
    numberOfPages: 212,
    rating: 4.21,
  },
  {
    id: 22,
    category: "Fiction",
    title: "To Kill a Mockingbird",
    coverImage: "https://covers.openlibrary.org/b/id/8384476-L.jpg",
    description:
      "A novel about racial injustice and moral growth in the American South.",
    authorName: "Harper Lee",
    dateOfPublication: "1960-07-11",
    numberOfPages: 281,
    rating: 4.27,
  },
  {
    id: 23,
    category: "Non-Fiction",
    title: "Sapiens: A Brief History of Humankind",
    coverImage: "https://covers.openlibrary.org/b/id/8379890-L.jpg",
    description:
      "Yuval Noah Harari explores the history and evolution of Homo sapiens.",
    authorName: "Yuval Noah Harari",
    dateOfPublication: "2011-06-04",
    numberOfPages: 498,
    rating: 4.39,
  },
  {
    id: 24,
    category: "Biography",
    title: "Steve Jobs",
    coverImage: "https://covers.openlibrary.org/b/id/8396678-L.jpg",
    description: "Walter Isaacson's biography of Apple co-founder Steve Jobs.",
    authorName: "Walter Isaacson",
    dateOfPublication: "2011-10-24",
    numberOfPages: 630,
    rating: 4.15,
  },
  {
    id: 25,
    category: "Science",
    title: "The Selfish Gene",
    coverImage: "https://covers.openlibrary.org/b/id/8232332-L.jpg",
    description:
      "Richard Dawkins introduces the gene-centered view of evolution.",
    authorName: "Richard Dawkins",
    dateOfPublication: "1976-03-15",
    numberOfPages: 360,
    rating: 4.13,
  },
  {
    id: 26,
    category: "Fiction",
    title: "1984",
    coverImage: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
    description: "A dystopian novel about totalitarianism and surveillance.",
    authorName: "George Orwell",
    dateOfPublication: "1949-06-08",
    numberOfPages: 328,
    rating: 4.18,
  },
  {
    id: 27,
    category: "Non-Fiction",
    title: "Thinking, Fast and Slow",
    coverImage: "https://covers.openlibrary.org/b/id/8235115-L.jpg",
    description:
      "Daniel Kahneman explains the dual systems that drive the way we think.",
    authorName: "Daniel Kahneman",
    dateOfPublication: "2011-10-25",
    numberOfPages: 499,
    rating: 4.1,
  },
  {
    id: 28,
    category: "Biography",
    title: "The Diary of a Young Girl",
    coverImage: "https://covers.openlibrary.org/b/id/8225636-L.jpg",
    description: "The writings of Anne Frank during the Nazi occupation.",
    authorName: "Anne Frank",
    dateOfPublication: "1947-06-25",
    numberOfPages: 283,
    rating: 4.19,
  },
  {
    id: 29,
    category: "Science",
    title: "Cosmos",
    coverImage: "https://covers.openlibrary.org/b/id/8232331-L.jpg",
    description:
      "Carl Sagan’s exploration of the universe and our place in it.",
    authorName: "Carl Sagan",
    dateOfPublication: "1980-09-01",
    numberOfPages: 396,
    rating: 4.36,
  },
  {
    id: 30,
    category: "Fiction",
    title: "Pride and Prejudice",
    coverImage: "https://covers.openlibrary.org/b/id/8232824-L.jpg",
    description: "A romantic novel of manners in early 19th century England.",
    authorName: "Jane Austen",
    dateOfPublication: "1813-01-28",
    numberOfPages: 279,
    rating: 4.26,
  },
  {
    id: 31,
    category: "Non-Fiction",
    title: "Educated",
    coverImage: "https://covers.openlibrary.org/b/id/8756547-L.jpg",
    description: "A memoir about a woman who grew up in a survivalist family.",
    authorName: "Tara Westover",
    dateOfPublication: "2018-02-18",
    numberOfPages: 352,
    rating: 4.47,
  },
  {
    id: 32,
    category: "Biography",
    title: "Becoming",
    coverImage: "https://covers.openlibrary.org/b/id/9252155-L.jpg",
    description:
      "Michelle Obama’s powerful memoir of her journey to the White House.",
    authorName: "Michelle Obama",
    dateOfPublication: "2018-11-13",
    numberOfPages: 426,
    rating: 4.54,
  },
  {
    id: 33,
    category: "Science",
    title: "The Gene: An Intimate History",
    coverImage: "https://covers.openlibrary.org/b/id/8589214-L.jpg",
    description:
      "Siddhartha Mukherjee explains the history and future of genetics.",
    authorName: "Siddhartha Mukherjee",
    dateOfPublication: "2016-05-17",
    numberOfPages: 608,
    rating: 4.32,
  },
  {
    id: 34,
    category: "Fiction",
    title: "The Great Gatsby",
    coverImage: "https://covers.openlibrary.org/b/id/7352161-L.jpg",
    description: "A tragic love story set in the roaring twenties.",
    authorName: "F. Scott Fitzgerald",
    dateOfPublication: "1925-04-10",
    numberOfPages: 180,
    rating: 3.93,
  },
  {
    id: 35,
    category: "Non-Fiction",
    title: "Outliers",
    coverImage: "https://covers.openlibrary.org/b/id/7162261-L.jpg",
    description: "Malcolm Gladwell explores the factors behind high achievers.",
    authorName: "Malcolm Gladwell",
    dateOfPublication: "2008-11-18",
    numberOfPages: 309,
    rating: 4.18,
  },
  {
    id: 36,
    category: "Biography",
    title: "Einstein: His Life and Universe",
    coverImage: "https://covers.openlibrary.org/b/id/8232441-L.jpg",
    description: "A biography of Albert Einstein by Walter Isaacson.",
    authorName: "Walter Isaacson",
    dateOfPublication: "2007-04-10",
    numberOfPages: 675,
    rating: 4.21,
  },
  {
    id: 37,
    category: "Science",
    title: "Astrophysics for People in a Hurry",
    coverImage: "https://covers.openlibrary.org/b/id/8379914-L.jpg",
    description:
      "Neil deGrasse Tyson makes astrophysics accessible for everyone.",
    authorName: "Neil deGrasse Tyson",
    dateOfPublication: "2017-05-02",
    numberOfPages: 224,
    rating: 4.22,
  },
  {
    id: 38,
    category: "Fiction",
    title: "The Book Thief",
    coverImage: "https://covers.openlibrary.org/b/id/8232203-L.jpg",
    description: "A story narrated by Death during WWII in Nazi Germany.",
    authorName: "Markus Zusak",
    dateOfPublication: "2005-03-14",
    numberOfPages: 552,
    rating: 4.38,
  },
  {
    id: 39,
    category: "Non-Fiction",
    title: "Quiet: The Power of Introverts",
    coverImage: "https://covers.openlibrary.org/b/id/8235153-L.jpg",
    description: "Explores the strengths of introverts in a noisy world.",
    authorName: "Susan Cain",
    dateOfPublication: "2012-01-24",
    numberOfPages: 352,
    rating: 4.15,
  },
];
